/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAny2EVMMessageReceiver } from "./IAny2EVMMessageReceiver";
export type { IRouterClient } from "./IRouterClient";
